// GENERATED by scripts/dstack-image-measurements.sh (native/dstack-image-measurements,
// dstack-mr @ Dstack-TEE/dstack 3c877847). Do not hand-edit: re-run the script.
//
// MRTD/RTMR0-2 computed from dstack guest images as PUBLISHED on GitHub, after
// every measured file was checked against the release's sha256sum.txt
// (os_image_hash = sha256 of that file). Derived facts about published
// artifacts, keyed by os_image_hash; not a reviewed allowlist. Verified
// 2026-10-01 to reproduce the live NEAR AI TDs exactly (both images, all four
// registers).

import type { DstackImageMeasurements } from "./dstackImage.js";

export const DSTACK_IMAGE_MEASUREMENTS: readonly DstackImageMeasurements[] = Object.freeze([
  {
    "computedBy": "dstack-mr @ Dstack-TEE/dstack 3c877847",
    "image": "dstack-nvidia-0.5.11",
    "isDev": false,
    "measurementDocumentSha256": "71df80a6900f53c75fa804739a365b06a32caf7a14f1c89d16bcc350e437357e",
    "measurements": [
      {
        "mrtd": "df4d77c857de652bd0fafa343a2026b51071ee03773d076d283abf1a7d36ff91ffa279ee4a617ac664f7e2a2c8d5891b",
        "rtmr0": "bc122d143ab768565ba5c3774ff5f03a63c89a4df7c1f5ea38d3bd173409d14f8cbdcc36d40e703cccb996a9d9687590",
        "rtmr1": "ff61e68fa04516b1813d2d478397a97a58f9ccc402b6d96fb73f5e5104a4acf155913caec99a0c19afc16ae0f3a77726",
        "rtmr2": "4d662c04766145dfe084fd014969b19c387afe9bb1d4f972c6968d28a7a8b4937c414603a2cf446105eddce67a86f9ce",
        "shape": {
          "cpu_count": 64,
          "host_share_mode": "9p",
          "hotplug_off": true,
          "hugepages": false,
          "memory_size": 2199023255552,
          "num_gpus": 8,
          "num_nvswitches": 4,
          "ovmf_variant": "pre202505",
          "pci_hole64_size": 1125899906842624,
          "qemu_version": "9.2.1"
        }
      }
    ],
    "osImageHash": "a6eafc5f007f642d8ea90c7fa8881f1e6715720ccb531941a28218f4f26d7b02",
    "prerelease": false,
    "source": "https://github.com/Dstack-TEE/meta-dstack/releases/download/v0.5.11/dstack-nvidia-0.5.11.tar.gz (sha256sum.txt verified: 4 files; git_revision ce04e924e17e3cb9d38d258338cbe71e8c08d575)"
  },
  {
    "computedBy": "dstack-mr @ Dstack-TEE/dstack 3c877847",
    "image": "dstack-nvidia-0.5.5",
    "isDev": false,
    "measurementDocumentSha256": "e482b083a31637bb4be08f64cd9d991cee874d033b33e9b69b45f04d7010fc43",
    "measurements": [
      {
        "mrtd": "b24d3b24e9e3c16012376b52362ca09856c4adecb709d5fac33addf1c47e193da075b125b6c364115771390a5461e217",
        "rtmr0": "bc122d143ab768565ba5c3774ff5f03a63c89a4df7c1f5ea38d3bd173409d14f8cbdcc36d40e703cccb996a9d9687590",
        "rtmr1": "c0445b704e4c48139496ae337423ddb1dcee3a673fd5fb60a53d562f127d235f11de471a7b4ee12c9027c829786757dc",
        "rtmr2": "564622c7ddc55a53272cc9f0956d29b3f7e0dd18ede432720b71fd89e5b5d76cb0b99be7b7ff2a6a92b89b6b01643135",
        "shape": {
          "cpu_count": 64,
          "hotplug_off": true,
          "hugepages": false,
          "memory_size": 2199023255552,
          "num_gpus": 8,
          "num_nvswitches": 4,
          "pci_hole64_size": 1125899906842624,
          "qemu_version": "9.2.1"
        }
      }
    ],
    "osImageHash": "9b69bb1698bacbb6985409a2c272bcb892e09cdcea63d5399c6768b67d3ff677",
    "prerelease": false,
    "source": "https://github.com/Dstack-TEE/meta-dstack/releases/download/v0.5.5/dstack-nvidia-0.5.5.tar.gz (sha256sum.txt verified: 4 files; git_revision 25c25025c556ab2f797eeda3bab433f38a8ffb7a)"
  }
]);
