// Generated by `npm run catalog:audit:near-relay -- --print` from NEAR AI
// Cloud's public /v1/models after a privacy and metadata review of each relayed
// route (src/providers/catalog/nearRelay.ts). Do not add a route by hand: the
// fingerprint binds owner, limits, modalities, capability flags, accepted
// sampling parameters, every published price tier, and the reviewed privacy
// class. samplingParameters is the reviewed list the adapter forwards.

export interface ReviewedNearRelayRoute {
  catalogFingerprint: string;
  samplingParameters: readonly string[];
}

export const NEAR_RELAY_REVIEWED_AT = "2026-10-01T00:00:00.000Z";
/** sha256 of the exact catalog bytes reviewed (recorded copy). */
export const NEAR_RELAY_REVIEWED_SOURCE_SHA256 = "e519a168af17c19a19aaeb966edd1df8a58690b399650832e4463b43d60a51c6";

export const NEAR_RELAY_REVIEWED_ROUTES: Readonly<Record<string, ReviewedNearRelayRoute>> = {
  "anthropic/claude-fable-5": {"catalogFingerprint":"7670dcf85d5a6c7c839d3413c4e2f9f0b9699cbb19f2fe6264207644dbe19bca","samplingParameters":["max_tokens","stop"]},
  "anthropic/claude-fable-5-1": {"catalogFingerprint":"409155f0c36492e5c22d8bf7eb4d1fc6e6677b3d69d66c730b8511d70692cc07","samplingParameters":["max_tokens","stop"]},
  "anthropic/claude-haiku-4-5": {"catalogFingerprint":"b7962e1aaf7f33e97e047f7474719df7435aa915f593b38b128f491bdc8913e5","samplingParameters":["max_tokens","stop","temperature","top_k","top_p"]},
  "anthropic/claude-opus-4-6": {"catalogFingerprint":"60c3c88cf7a62a9093f6aea5241f3c7a4d92a622897f72a7081399e617ad1cfa","samplingParameters":["max_tokens","stop","temperature","top_k","top_p"]},
  "anthropic/claude-opus-4-7": {"catalogFingerprint":"9daad8a75fb8823e11da4119cdf15fdce3163d20bf68c631c3e9fee135e118dc","samplingParameters":["max_tokens","stop","temperature","top_k","top_p"]},
  "anthropic/claude-opus-5": {"catalogFingerprint":"bb0fe05bf186023015b5ea978fb061d768ca35ff8f4b1d568f0f29e501bacf53","samplingParameters":["max_tokens","stop"]},
  "anthropic/claude-opus-5-5": {"catalogFingerprint":"1eb50dc0f471da6be13362778613febb485f762d17927459db0a5775a8548750","samplingParameters":["max_tokens","stop"]},
  "anthropic/claude-sonnet-4-5": {"catalogFingerprint":"4c63025e5a3d8dc6a5b28371e7dc56a81ceea37c7beffaed6dd897ddbe53e128","samplingParameters":["max_tokens","stop","temperature","top_k","top_p"]},
  "anthropic/claude-sonnet-4-6": {"catalogFingerprint":"f35d09575d7d7acbb3d655d6cda426c71fb5b103c75ef30e38e2f85af0f784c1","samplingParameters":["max_tokens","stop","temperature","top_k","top_p"]},
  "anthropic/claude-sonnet-5": {"catalogFingerprint":"742165557446b14510bfe508d9216ff8f0966206709a5286c09b61591eda57c3","samplingParameters":["max_tokens","stop"]},
  "anthropic/claude-sonnet-5-5": {"catalogFingerprint":"5488457898cbc971335ab2b585553b9384f5d3243a8989b053d0cafa5eed5ad5","samplingParameters":["max_tokens","stop"]},
  "deepseek/deepseek-v4.1-flash": {"catalogFingerprint":"4ddc9f2077adac1fe091892eb5b2fb644eb7fe483ebf2719340eb2d2cd3cffb5","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","repetition_penalty","stop","temperature","top_k","top_p"]},
  "google/gemini-2.5-flash": {"catalogFingerprint":"7dee137941212e3ef38b8e50713820e7888b5a832bb2a333e9b2244f201e6a4c","samplingParameters":["max_tokens","stop","temperature","top_k","top_p"]},
  "google/gemini-2.5-flash-lite": {"catalogFingerprint":"6bf48b462578d19d99ae5483c6033a4492dc22a0f0b55c26dc2a1baec523e4f7","samplingParameters":["max_tokens","stop","temperature","top_k","top_p"]},
  "google/gemini-2.5-pro": {"catalogFingerprint":"719c8bccd74bc07df537e3298effb8129b3f6e9d7d0b39ef413d6e6ca6d0cb78","samplingParameters":["max_tokens","stop","temperature","top_k","top_p"]},
  "google/gemini-3.1-flash-lite": {"catalogFingerprint":"ffd61bae021dbc1c72f29e6775aa71cffc9dc9940522c82b3dae0b2881ffb6de","samplingParameters":["max_tokens","stop","temperature","top_k","top_p"]},
  "google/gemini-3.5-flash": {"catalogFingerprint":"b94c70681341ec5c47f2cdc27839d1263ac15350448ede29b89e2110e55fd7fa","samplingParameters":["max_tokens","stop","temperature","top_k","top_p"]},
  "openai/gpt-4.1": {"catalogFingerprint":"bf31b9835ecb53940c0c6ddb6b9c163ab4c24e01e291c0cdb07fe16db68ac712","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-4.1-mini": {"catalogFingerprint":"e1e06b93264abd3db18d6ac402df768ed4abbc60fc5c005d3640096ca6febcdd","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-4.1-nano": {"catalogFingerprint":"684aaea86a04dd0e827bc49173c8d72e90bda9c9e8b96b7e50d728f6a62469c4","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-5": {"catalogFingerprint":"005eb9aedce0dd34d190571e19fc90b8a5a9c768e01bec026f5ae294c03a27f3","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-5-mini": {"catalogFingerprint":"3de96e19f4c4abb21e8a18df4e591b77171f6eb3fe566638b6bda4579e738379","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-5-nano": {"catalogFingerprint":"a37db879643a5d170f30452cc9d7552c2829c6d7652c0ef0435229937bea679d","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-5.1": {"catalogFingerprint":"2a26a9f85755fec9662b981362b24f5fa6858aa6382071a7f43ea5d2b3eb454a","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-5.2": {"catalogFingerprint":"0e68429c892b659811a80d39b234c04d1f05749b9d3be91c6307c2ed6196e61d","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-5.4": {"catalogFingerprint":"53f1ed6f65dd29cafbd1b4380a53b49b515f4c1027488aecdcce8fd22a811695","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-5.4-mini": {"catalogFingerprint":"80c56dc97fc6e429cbb26522540279c1b600104bf9d91f98f3c2aede59a1b0a0","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-5.4-nano": {"catalogFingerprint":"77fb0373f3a258918d8c5ae74a8ab9879af1318c40b97c8a19f710640fb35976","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-5.5": {"catalogFingerprint":"2d998e611da22c0449464f703ffbd00d8aeef665d4e05e9e6850bec36757584d","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-5.6-luna": {"catalogFingerprint":"3aad2ccd153d8d384b0f7cccf8f976c499c8d8f2cf9bca7657cda19b56187a55","samplingParameters":["frequency_penalty","logit_bias","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-5.6-sol": {"catalogFingerprint":"0b7c44b7765dd7c18b7b1ceb1abff6b506daf5af0db5294ed8f81f69f68f9dc2","samplingParameters":["frequency_penalty","logit_bias","max_tokens","presence_penalty","seed","stop","temperature","top_p"]},
  "openai/gpt-6-astra": {"catalogFingerprint":"45b735e4b8a3a2d60ef5f5cf9ef625bcf8ade100b7b1abfcdaaeabfa6d15308e","samplingParameters":["max_tokens"]},
  "openai/gpt-6-luna": {"catalogFingerprint":"6d6f28c4edcecba175a968198d42034ed7ecbe5900870cd99c55485990136217","samplingParameters":["max_tokens"]},
  "openai/gpt-6-sol": {"catalogFingerprint":"34eac766f20eea98f88248f321da7e3bab1dcb2fd4a660d67a3ab9944c857246","samplingParameters":["max_tokens"]},
  "openai/gpt-6.1-sol": {"catalogFingerprint":"f8b30269d038396580864e77d0d2dd260a1aff5ef49f7f15856634b21aaca780","samplingParameters":["max_tokens"]},
  "openai/o3": {"catalogFingerprint":"9b8a9d971fca086ed30406024734c1ecaa8602749ad94f00a0a71560e3b9d305","samplingParameters":["max_tokens","seed","stop"]},
  "openai/o3-mini": {"catalogFingerprint":"ca0457f8d5b0224da88a4365650147f74003d7262f4e39ec93d7a0d8ae511eda","samplingParameters":["max_tokens","seed","stop"]},
  "openai/o4-mini": {"catalogFingerprint":"6e87c528500e00ec3a385dfe873edcfb880cc97bb8f209919b7ec82a931518c2","samplingParameters":["max_tokens","seed","stop"]},
  "qwen/qwen3.7-max": {"catalogFingerprint":"78bd90c7cada1d05980115400661fa258b09e1c7f0fcfc813ca61e068b93f652","samplingParameters":["frequency_penalty","max_tokens","presence_penalty","seed","stop","temperature","top_k","top_p"]},
  "x-ai/grok-4.6": {"catalogFingerprint":"116e93c1ba359ef07d02cae1bd1aa4f4a54596d19c4938c65607ced4cb4f7fa6","samplingParameters":["max_tokens","seed","temperature","top_p"]},
  "x-ai/grok-4.7": {"catalogFingerprint":"0f8849de8957cfefd65ec792f3da53727b032721e327eabcf69948506951139f","samplingParameters":["max_tokens","seed","temperature","top_p"]}
};
