#!/usr/bin/env bash
# Replay a Docker Official Image build from the recipe read out of the deployed
# artifact.
#
# =============================================================================
# EVERY ARGUMENT COMES FROM THE RECIPE FILE
# =============================================================================
#
# Nothing is hard-coded here: not the source URL, not the commit, not the parent
# image, not the frontend, not a build argument. They are read from the JSON
# that scripts/provenance/doi-source-recipe.ts extracted from the deployed
# image's own SLSA statement.
#
# That is the whole point. A replay whose inputs came from a document this
# project maintains would be a test of our bookkeeping; a replay whose inputs
# came from the artifact is a test of the artifact.
#
# =============================================================================
# WHERE THIS DEPARTS FROM docker-library, AND WHY
# =============================================================================
#
# The upstream invocation is generated by meta.jq in docker-library/meta-scripts.
# Two differences, both deliberate:
#
#   --provenance=false --sbom=false
#       Upstream passes `--provenance=mode=max` and an SBOM generator. Inline
#       attestations turn the OCI output into an index carrying extra manifests,
#       which would make a manifest-to-manifest comparison structurally
#       impossible. The image manifest itself is unaffected by the flag, which
#       is why this is a safe departure and not a convenient one.
#
#   --no-cache
#       Upstream builds on a fresh worker. Here the same recipe is replayed more
#       than once in one job to test whether it is deterministic AT ALL, and a
#       warm cache would make the second run agree with the first for a reason
#       that has nothing to do with the recipe.
#
# No --tag is passed. Tags land in the OCI layout's index descriptor, never in
# the manifest blob the comparison reads.
#
#   replay-doi-build.sh <recipe.json> <output.tar>
#
# SOURCE_DATE_EPOCH is honoured from the environment if set, because buildx
# propagates it into the build. The recorded docker-library invocation did NOT
# set it; running with and without is how both halves of that fork get tested
# rather than argued about.

#
# REPLAY_DRY_RUN=1 prints the invocation and exits without building. That is how
# the offline test asserts the arguments actually carry the pinned parent, the
# pinned frontend and the pinned commit, rather than a reviewer reading the
# script and believing it.

set -euo pipefail

recipe="${1:?usage: replay-doi-build.sh <recipe.json> <output.tar>}"
dest="${2:?usage: replay-doi-build.sh <recipe.json> <output.tar>}"
dry_run="${REPLAY_DRY_RUN:-}"

for tool in docker jq; do
  if [ -n "$dry_run" ] && [ "$tool" = "docker" ]; then continue; fi
  command -v "$tool" >/dev/null || { echo "required tool '$tool' is missing" >&2; exit 1; }
done

build_url=$(jq -r '.source.buildUrl' "$recipe")
dockerfile=$(jq -r '.source.dockerfile' "$recipe")
platform=$(jq -r '.build.platform' "$recipe")
frontend=$(jq -r '.build.frontend // empty' "$recipe")

if [ -z "$build_url" ] || [ "$build_url" = "null" ]; then
  echo "REFUSING: the recipe carries no build url." >&2
  exit 1
fi
case "$platform" in
  linux/amd64) ;;
  *)
    # A replay on the wrong platform produces a confident answer about a
    # different image. Refuse rather than emulate: emulation leaves fingerprints
    # in the result, which is how the earlier dstack-ingress near-miss happened.
    echo "REFUSING: recipe platform is '$platform'; this replay only runs native linux/amd64." >&2
    exit 1
    ;;
esac

args=(
  build
  --progress=plain
  --platform "$platform"
  --no-cache
  --provenance=false
  --sbom=false
  --file "$dockerfile"
)

# Named contexts. Without them the build resolves `FROM alpine:3.23` to
# whatever that tag points at today, which is a different image, and the
# difference would be silently attributed to the source.
while IFS= read -r context; do
  [ -n "$context" ] || continue
  args+=(--build-context "$context")
done < <(jq -r '.build.buildContexts | to_entries[] | "\(.key)=\(.value)"' "$recipe")

while IFS= read -r build_arg; do
  [ -n "$build_arg" ] || continue
  args+=(--build-arg "$build_arg")
done < <(jq -r '.build.buildArgs | to_entries[] | "\(.key)=\(.value)"' "$recipe")

if [ -n "$frontend" ]; then
  args+=(--build-arg "BUILDKIT_SYNTAX=$frontend")
fi

# The deployed manifest's annotations, handed to the rebuild as inputs.
#
# This is DELIBERATELY GENEROUS and the judge knows it: supplying the target's
# own metadata means the rebuild did not produce it, so
# `--annotations-from-deployed` forces bindingEligible to false even on an exact
# match. The generosity is here so that a failure cannot be waved away as "you
# just did not set the annotations".
while IFS= read -r annotation; do
  [ -n "$annotation" ] || continue
  args+=(--annotation "manifest,manifest-descriptor:$annotation")
done < <(jq -r '.deployedArtifact.annotations | to_entries[] | "\(.key)=\(.value)"' "$recipe")

args+=(--output "type=oci,dest=$dest")
args+=("$build_url")

printf 'docker buildx'
printf ' %q' "${args[@]}"
printf '\n'

if [ -n "$dry_run" ]; then
  exit 0
fi

docker buildx "${args[@]}"
